99Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :edit, :create, :update]

  resources :cat_rental_requests, except: [:destroy]
end

99Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

99Cats/app/models/cat.rb
class Cat < ApplicationRecord
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: ['brown', 'black', 'white', 'orange', 'grey']
  validates :sex, inclusion: ['M', 'F']

  def age
    (Time.now.to_date.year - self.birth_date.year)
  end

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: "CatRentalRequest"

end

99Cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: ["PENDING", "APPROVED", "DENIED"]
  #validate does_not_overlap_approved_request

  belongs_to :cat, dependent: :destroy,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: "Cat"

  private

  def overlapping_requests
    if self.persisted?
      CatRentalRequest
      .where("cat_id = #{self.cat_id}")
      .where("#{self.id} != id")
      .where(<<-SQL)
        (#{self.end_date} > start_date AND
        #{self.start_date} < end_date) OR
        (end_date BETWEEN #{self.start_date} AND #{self.end_date}) OR
        (start_date BETWEEN #{self.start_date} AND #{self.end_date})
        SQL
    else
      CatRentalRequest
        .where("#{self.end_date} > start_date AND
          #{self.start_date} < end_date AND cat_id = #{self.cat_id}")
    end
  end

  def overlapping_approved_requests
    overlapping_requests.where(status == "APPROVED")
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors[:base] << "Cat can't be in two places at once"
    end
  end

end

99Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

99Cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @cats = Cat.all
    @cat_rentals = CatRentalRequest.all
  end

  def show
    render :show
  end

  def new
    @cats = Cat.all
    @cat_rental = CatRentalRequest.new
  end

  def create
    @cat_rental = CatRentalRequest.new(cat_rental_params)
    if @cat_rental.save
      redirect_to cat_url(@cat_rental)
    else
      render :show
    end
  end

  private
  def cat_rental_params
    params.require(:cat_rental).permit(:cat_id, :start_date, :end_date, :status)
  end
end

99Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    # fail
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :description, :sex, :color, :birth_date)
  end
end

99Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

99Cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

99Cats/app/helpers/cats_helper.rb
module CatsHelper
end

99Cats/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">
  <label for="cat">Select a Cat</label>
  <select id="cat" name="cat_rental[cat_id]">

    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %> </option>
    <% end %>

  </select>
  <label for="start_date">Start Date</label>
  <input id="start_date" name="cat_rental[start_date]" type="date" value="<%= @cat_rental.start_date %>">

  <label for="end_date">End Date</label>
  <input id="end_date" name="cat_rental[end_date]" type="date" value="<%= @cat_rental.end_date %>">

  </select>

  <input type="submit" value="Request Rental">
</form>

99Cats/app/views/cats/_cat.html.erb
<li>
  <%= link_to cat.name, cat_url(cat) %>
</li>

99Cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url  = cat_url(cat)%>
  <% else %>
    <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name</label>
  <input id="name"  type="text" name="cat[name]" value = "<%= @cat.name ? @cat.name : "" %>">

  <br>

  <label for="sex">Sex
  M<input type="radio" name="cat[sex]" value="M" checked= "<%= @cat.sex == "M" ? "checked" : "" %>">
  F<input type="radio" name="cat[sex]" value="F" checked= "<%= @cat.sex == "F" ? "checked" : "" %>">
  </label>

  <br>

  <label for="date">Birth Date</label>
  <input id="date" name="cat[birth_date]" type="date" value = "<%= @cat.birth_date ? @cat.birth_date : "" %>">

  <br>

  <label for="description">Description</label>
  <textarea id="description" name="cat[description]" rows="10" cols="20">
    <%= @cat.description %>
  </textarea>
  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= @cat.color ? "" : "selected" %>>Select color</option>
    <option value="brown" <%= @cat.color == "brown" ? "selected" : "" %>>Brown</option>
    <option value="black" <%= @cat.color == "black" ? "selected" : "" %>>Black</option>
    <option value="white" <%= @cat.color == "white" ? "selected" : "" %>>White</option>
    <option value="orange" <%= @cat.color == "orange" ? "selected" : "" %>>Orange</option>
    <option value="grey" <%= @cat.color == "grey" ? "selected" : "" %>>Grey</option>
  </select>

  <br>

  <input type="submit" value="<%= action == :edit ? "Edit Cat" : "Add Cat" %>">
</form>

99Cats/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>
<%= render "form", cat: @cat, action: :edit %>

99Cats/app/views/cats/index.html.erb
<h1> All the cats! </h1>

<ul>
  <%= render @cats %>
</ul>

99Cats/app/views/cats/new.html.erb
<h1>New Cat</h1>
<%= render "form", cat: @cat, action: :new %>

99Cats/app/views/cats/show.html.erb
<h1> <%= @cat.name %></h1>

<table>
  <tr>
    <th>Color</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>

  <tr>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.age %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.description %> </td>
  </tr>
</table>

<h2> Cat Rentals! </h2>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>

  <tr>
    <td> <%= @cat.cat_rental_requests.first.start_date %> </td>
    <td> <%= @cat.cat_rental_requests.first.end_date %> </td>
    <td> <%= @cat.cat_rental_requests.first.status %> </td>
  </tr>
</table>

99Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>